package com.ar.crm2.application.usuario.service;

import com.ar.crm2.application.identity.model.IdentityProvisioningException;
import com.ar.crm2.application.identity.model.ProvisionedIdentity;
import com.ar.crm2.application.identity.port.out.DeleteIdentityPort;
import com.ar.crm2.application.identity.port.out.ProvisionIdentityPort;
import com.ar.crm2.application.identity.port.out.SetIdentityAttributesPort;
import com.ar.crm2.application.usuario.command.CreateUsuarioCommand;
import com.ar.crm2.application.usuario.port.out.SaveUsuarioPort;
import com.ar.crm2.model.entity.Usuario;
import com.ar.crm2.model.vo.RolId;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InOrder;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link CreateUsuarioService} Keycloak provisioning flow.
 * <p>
 * Covers: the call order provision → setAttributes → save, the contract that
 * {@code usuario_id} is pushed to Keycloak using the id generated by
 * {@code Usuario.create(...)} BEFORE the local save, the compensation deletes
 * that fire when either the pre-save attribute sync or the local save fails,
 * and the fast-fail behavior when Keycloak itself is unreachable.
 */
@ExtendWith(MockitoExtension.class)
class CreateUsuarioServiceKeycloakTest {

    private static final String NOMBRE = "Juan Perez";
    private static final String CORREO = "juan@example.com";
    private static final String PASSWORD = "TempPass123!";
    private static final String KEYCLOAK_ID = "kc-uuid-new-user-123";
    private static final UUID ROL_ID = UUID.randomUUID();

    @Mock
    private SaveUsuarioPort savePort;

    @Mock
    private ProvisionIdentityPort provisionPort;

    @Mock
    private DeleteIdentityPort deleteIdentityPort;

    @Mock
    private SetIdentityAttributesPort setAttributesPort;

    @InjectMocks
    private CreateUsuarioService service;

    // ── Happy path ─────────────────────────────────────────────────

    @Nested
    @DisplayName("successful Keycloak provisioning")
    class ProvisionamientoExitoso {

        @Test
        @DisplayName("invokes ports in the order: provision → setAttributes → save")
        void create_exitoso_ordenProvisionSyncSave() {
            // Given
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenAnswer(inv -> inv.getArgument(0));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When
            service.create(cmd);

            // Then
            InOrder inOrder = inOrder(provisionPort, setAttributesPort, savePort);
            inOrder.verify(provisionPort).provision(CORREO, PASSWORD, true);
            inOrder.verify(setAttributesPort).setAttributes(eq(KEYCLOAK_ID), anyMap());
            inOrder.verify(savePort).save(any(Usuario.class));
        }

        @Test
        @DisplayName("returns a saved usuario with the provisioned keycloakId")
        void create_exitoso_guardaConKeycloakId() {
            // Given
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenAnswer(inv -> inv.getArgument(0));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When
            Usuario result = service.create(cmd);

            // Then
            assertEquals(KEYCLOAK_ID, result.getKeycloakId());
            assertEquals(CORREO, result.getCorreo());
            assertEquals(NOMBRE, result.getNombre());
            verify(provisionPort).provision(CORREO, PASSWORD, true);
            verify(savePort).save(any(Usuario.class));
        }

        @Test
        @DisplayName("provisions with enabled=true (VERIFY_EMAIL triggers the verification email)")
        void create_exitoso_enviaVERIFY_EMAIL() {
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenAnswer(inv -> inv.getArgument(0));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );
            service.create(cmd);

            verify(provisionPort).provision(CORREO, PASSWORD, true);
        }
    }

    // ── Pre-save Keycloak attribute sync (usuario_id) ──────────────

    @Nested
    @DisplayName("pre-save Keycloak attribute sync")
    class PreSaveKeycloakAttributeSync {

        @Test
        @DisplayName("syncs the same usuario_id built by Usuario.create() to Keycloak before local save")
        void create_exitoso_sincronizaUsuarioIdEnKeycloak() {
            // Given
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenAnswer(inv -> inv.getArgument(0));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When
            Usuario result = service.create(cmd);

            // Then — capture the entity handed to savePort
            ArgumentCaptor<Usuario> entityCaptor = ArgumentCaptor.forClass(Usuario.class);
            verify(savePort).save(entityCaptor.capture());
            Usuario savedEntity = entityCaptor.getValue();

            // And the map handed to setAttributesPort
            @SuppressWarnings("unchecked")
            ArgumentCaptor<Map<String, String>> attrsCaptor = ArgumentCaptor.forClass(Map.class);
            verify(setAttributesPort).setAttributes(eq(KEYCLOAK_ID), attrsCaptor.capture());

            // The id pushed to Keycloak must equal the id of the entity persisted locally
            assertEquals(savedEntity.getId().value().toString(),
                attrsCaptor.getValue().get("usuario_id"));
            assertEquals(result.getId(), savedEntity.getId());
        }

        @Test
        @DisplayName("calls setAttributesPort exactly once with the provisioned keycloakId")
        void create_exitoso_llamaSetAttributesUnaVez() {
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenAnswer(inv -> inv.getArgument(0));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            service.create(cmd);

            verify(setAttributesPort, times(1)).setAttributes(eq(KEYCLOAK_ID), anyMap());
        }

        @Test
        @DisplayName("compensates by deleting Keycloak user when pre-save setAttributes fails")
        void create_setAttributesFalla_compensaEliminaKeycloak() {
            // Given — provision succeeds, pre-save attribute sync fails
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            doThrow(new IdentityProvisioningException(
                "Keycloak unavailable",
                IdentityProvisioningException.Reason.CONNECTION_FAILURE
            )).when(setAttributesPort).setAttributes(eq(KEYCLOAK_ID), anyMap());

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When / Then — original failure is surfaced, compensation delete fires
            IdentityProvisioningException thrown = assertThrows(
                IdentityProvisioningException.class,
                () -> service.create(cmd)
            );
            assertEquals(IdentityProvisioningException.Reason.CONNECTION_FAILURE,
                thrown.getReason());
            verify(deleteIdentityPort).delete(KEYCLOAK_ID);
            verify(savePort, never()).save(any());
        }

        @Test
        @DisplayName("rethrows original setAttributes failure when compensation delete also fails")
        void create_setAttributesFalla_compensacionFalla_rethrowsOriginal() {
            // Given — provision succeeds, pre-save attribute sync fails, compensation delete fails
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            doThrow(new IdentityProvisioningException(
                "Keycloak unavailable",
                IdentityProvisioningException.Reason.CONNECTION_FAILURE
            )).when(setAttributesPort).setAttributes(eq(KEYCLOAK_ID), anyMap());
            doThrow(new RuntimeException("Keycloak unreachable"))
                .when(deleteIdentityPort).delete(KEYCLOAK_ID);

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When / Then — original setAttributes failure propagates
            IdentityProvisioningException thrown = assertThrows(
                IdentityProvisioningException.class,
                () -> service.create(cmd)
            );
            assertEquals(IdentityProvisioningException.Reason.CONNECTION_FAILURE,
                thrown.getReason());
            verify(savePort, never()).save(any());
        }
    }

    // ── Save failure compensation ─────────────────────────────────

    @Nested
    @DisplayName("local save fails after Keycloak sync — compensation delete")
    class CompensacionSaveFalla {

        @Test
        @DisplayName("deletes Keycloak user when local save throws after attribute sync")
        void create_saveFalla_compensaEliminaKeycloak() {
            // Given — provision succeeds, pre-save attribute sync succeeds (default
            // no-op for void mocks), local save throws
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenThrow(new RuntimeException("DB constraint violation"));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When / Then
            assertThrows(RuntimeException.class, () -> service.create(cmd));
            verify(deleteIdentityPort).delete(KEYCLOAK_ID);
        }

        @Test
        @DisplayName("rethrows original save exception even if compensation delete fails")
        void create_compensacionFalla_rethrowsOriginal() {
            // Given
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenReturn(new ProvisionedIdentity(KEYCLOAK_ID, CORREO));
            when(savePort.save(any(Usuario.class)))
                .thenThrow(new RuntimeException("DB error"));
            doThrow(new RuntimeException("Keycloak unreachable"))
                .when(deleteIdentityPort).delete(KEYCLOAK_ID);

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When / Then — original save failure propagates
            RuntimeException thrown = assertThrows(RuntimeException.class,
                () -> service.create(cmd));
            assertEquals("DB error", thrown.getMessage());
        }
    }

    // ── Keycloak unreachable ──────────────────────────────────────

    @Nested
    @DisplayName("Keycloak creation fails")
    class KeycloakFalla {

        @Test
        @DisplayName("fails fast when Keycloak is unreachable — no setAttributes and no local save")
        void create_keycloakFalla_noGuardaLocal() {
            // Given
            when(provisionPort.provision(CORREO, PASSWORD, true))
                .thenThrow(new IdentityProvisioningException(
                    "Connection refused",
                    IdentityProvisioningException.Reason.CONNECTION_FAILURE
                ));

            CreateUsuarioCommand cmd = new CreateUsuarioCommand(
                NOMBRE, CORREO, ROL_ID, null, PASSWORD
            );

            // When / Then
            IdentityProvisioningException thrown = assertThrows(
                IdentityProvisioningException.class,
                () -> service.create(cmd)
            );
            assertEquals(IdentityProvisioningException.Reason.CONNECTION_FAILURE,
                thrown.getReason());
            verify(savePort, never()).save(any());
            verify(setAttributesPort, never()).setAttributes(any(), any());
        }
    }
}
